"""add geofence fields to routes

Revision ID: 38353bbc7519
Revises: 44ad32f3ec58
Create Date: 2026-02-09 16:51:15.986326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38353bbc7519'
down_revision = '44ad32f3ec58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_point_gps', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ending_point_gps', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('route_radius_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('route_radius_km')
        batch_op.drop_column('ending_point_gps')
        batch_op.drop_column('starting_point_gps')

    # ### end Alembic commands ###
